### ISSUE TITLE
pmd-unit-tests%3AJUnit4TestShouldUseAfterAnnotation applies to testng test

### ISSUE THREAD

**Issue by mpet** [jborgers/sonar-pmd#253]
https://community.sonarsource.com/t/rule-key-pmd-unit-tests-3ajunit4testshoulduseafterannotation-applies-to-testng-test/37838

br,

//mike

**Comment by jensgerdes** [comment]
Hi @mpet 

Thank you for opening this issue. I am afraid, this is still not the right place.
This behaviour is defined in the PMD rule [JUnit4TestShouldUseAfterAnnotation](https://pmd.github.io/latest/pmd_rules_java_bestpractices.html#junit4testshoulduseafterannotation) which is part of the [pmd project](https://github.com/pmd/pmd).

Your issue is being discussed here: pmd/pmd#2316
