### ISSUE TITLE
Does the latest Version, 3.4.0, supports SonarQube versions 10.2 and 10.3?

### ISSUE THREAD

**Issue by RobSHK** [jborgers/sonar-pmd#418]

**Comment by readonlyuser1** [comment]
?
`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar (default-cli) on project xxx: Execution default-cli of goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar failed: An API incompatibility was encountered while executing org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594:sonar: java.lang.NoSuchMethodError: 'org.sonar.api.rules.RulePriority org.sonar.api.rules.RulePriority.valueOfString(java.lang.String)'
08:13:04 [ERROR] -----------------------------------------------------
08:13:04 [ERROR] realm =    plugin>org.sonarsource.scanner.maven:sonar-maven-plugin:3.10.0.2594
08:13:04 [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
08:13:04 [ERROR] urls[0] = file:xxx/.m2/repository/org/sonarsource/scanner/maven/sonar-maven-plugin/3.10.0.2594/sonar-maven-plugin-3.10.0.2594.jar
08:13:04 [ERROR] urls[1] = file:xxx/.m2/repository/org/codehaus/plexus/plexus-sec-dispatcher/2.0/plexus-sec-dispatcher-2.0.jar
08:13:04 [ERROR] urls[2] = file:/xxx/.m2/repository/org/codehaus/plexus/plexus-utils/3.4.1/plexus-utils-3.4.1.jar
08:13:04 [ERROR] urls[3] = file:/xxx/.m2/repository/org/codehaus/plexus/plexus-cipher/2.0/plexus-cipher-2.0.jar
08:13:04 [ERROR] urls[4] = file:/xxx/.m2/repository/org/sonarsource/scanner/api/sonar-scanner-api/2.16.3.1081/sonar-scanner-api-2.16.3.1081.jar
08:13:04 [ERROR] urls[5] = file:/xxx/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
08:13:04 [ERROR] Number of foreign imports: 1
08:13:04 [ERROR] import: Entry[import  from realm ClassRealm[project>xxx:1.1.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
`
`Caused by: java.lang.NoSuchMethodError: 'org.sonar.api.rules.RulePriority org.sonar.api.rules.RulePriority.valueOfString(java.lang.String)'
    at org.sonar.plugins.pmd.xml.factory.ActiveRulesRuleSetFactory.create (ActiveRulesRuleSetFactory.java:57)
    at org.sonar.plugins.pmd.xml.PmdRuleSets.create (PmdRuleSets.java:73)
    at org.sonar.plugins.pmd.xml.PmdRuleSets.from (PmdRuleSets.java:60)
    at org.sonar.plugins.pmd.PmdExecutor.dumpXml (PmdExecutor.java:150)
    at org.sonar.plugins.pmd.PmdExecutor.createRuleSet (PmdExecutor.java:136)
    at org.sonar.plugins.pmd.PmdExecutor.executeRules (PmdExecutor.java:123)
    at org.sonar.plugins.pmd.PmdExecutor.executePmd (PmdExecutor.java:89)
    at org.sonar.plugins.pmd.PmdExecutor.execute (PmdExecutor.java:75)
    at org.sonar.plugins.pmd.PmdSensor.execute (PmdSensor.java:71)`

**Comment by RobSHK** [comment]
@readonlyuser1 that means it is not supported, right?
Which SonarQube version do you use?

**Comment by readonlyuser1** [comment]
after 
`rm /opt/sonarqube/extensions/plugins/sonar-pmd-plugin-3.4.0.jar`
after this sonarqube works well

some help:
https://community.sonarsource.com/t/pmd-plugin-causes-sonar-maven-to-fail-with-sonarqube-10-2/99605/3
https://community.sonarsource.com/t/restriction-of-the-download-of-scanner-plugins-to-those-that-are-essentially-needed/75847/11

**Comment by juzi** [comment]
Same here, sonar-pmd-plugin-3.4.0 and Sonarqube 10.4 are note compatible.
